/* ── Item Database — English + Italian ─────────────────────────────────────
   Ported from the ShoppingList reference app. The per-item "aisle" number
   from the original is dropped here: aisle assignment is resolved live from
   an item's category against whichever supermarket's aisle list is active,
   so editing aisles in Settings immediately re-sorts existing items. */
const ITEM_DB = [
  // Fruit and Vegetables
  { name_en:'Apples', name_it:'Mele', category:'Fruit and Vegetables', emoji:'🍎' },
  { name_en:'Bananas', name_it:'Banane', category:'Fruit and Vegetables', emoji:'🍌' },
  { name_en:'Oranges', name_it:'Arance', category:'Fruit and Vegetables', emoji:'🍊' },
  { name_en:'Mangoes', name_it:'Manghi', category:'Fruit and Vegetables', emoji:'🥭' },
  { name_en:'Grapes', name_it:'Uva', category:'Fruit and Vegetables', emoji:'🍇' },
  { name_en:'Strawberries', name_it:'Fragole', category:'Fruit and Vegetables', emoji:'🍓' },
  { name_en:'Watermelon', name_it:'Anguria', category:'Fruit and Vegetables', emoji:'🍉' },
  { name_en:'Pineapple', name_it:'Ananas', category:'Fruit and Vegetables', emoji:'🍍' },
  { name_en:'Avocado', name_it:'Avocado', category:'Fruit and Vegetables', emoji:'🥑' },
  { name_en:'Lemon', name_it:'Limone', category:'Fruit and Vegetables', emoji:'🍋' },
  { name_en:'Lime', name_it:'Lime', category:'Fruit and Vegetables', emoji:'🍋' },
  { name_en:'Tomatoes', name_it:'Pomodori', category:'Fruit and Vegetables', emoji:'🍅' },
  { name_en:'Cucumber', name_it:'Cetriolo', category:'Fruit and Vegetables', emoji:'🥒' },
  { name_en:'Carrots', name_it:'Carote', category:'Fruit and Vegetables', emoji:'🥕' },
  { name_en:'Onions', name_it:'Cipolle', category:'Fruit and Vegetables', emoji:'🧅' },
  { name_en:'Garlic', name_it:'Aglio', category:'Fruit and Vegetables', emoji:'🧄' },
  { name_en:'Ginger', name_it:'Zenzero', category:'Fruit and Vegetables', emoji:'🫚' },
  { name_en:'Potatoes', name_it:'Patate', category:'Fruit and Vegetables', emoji:'🥔' },
  { name_en:'Sweet Potato', name_it:'Patata Dolce', category:'Fruit and Vegetables', emoji:'🍠' },
  { name_en:'Broccoli', name_it:'Broccoli', category:'Fruit and Vegetables', emoji:'🥦' },
  { name_en:'Cauliflower', name_it:'Cavolfiore', category:'Fruit and Vegetables', emoji:'🥦' },
  { name_en:'Spinach', name_it:'Spinaci', category:'Fruit and Vegetables', emoji:'🥬' },
  { name_en:'Lettuce', name_it:'Lattuga', category:'Fruit and Vegetables', emoji:'🥬' },
  { name_en:'Rocket (Arugula)', name_it:'Rucola', category:'Fruit and Vegetables', emoji:'🥬' },
  { name_en:'Zucchini', name_it:'Zucchine', category:'Fruit and Vegetables', emoji:'🥒' },
  { name_en:'Eggplant', name_it:'Melanzane', category:'Fruit and Vegetables', emoji:'🍆' },
  { name_en:'Bell Peppers', name_it:'Peperoni', category:'Fruit and Vegetables', emoji:'🫑' },
  { name_en:'Chilli Peppers', name_it:'Peperoncino', category:'Fruit and Vegetables', emoji:'🌶️' },
  { name_en:'Mushrooms', name_it:'Funghi', category:'Fruit and Vegetables', emoji:'🍄' },
  { name_en:'Celery', name_it:'Sedano', category:'Fruit and Vegetables', emoji:'🥬' },
  { name_en:'Spring Onions', name_it:'Cipollotti', category:'Fruit and Vegetables', emoji:'🌱' },
  { name_en:'Coriander (Fresh)', name_it:'Coriandolo Fresco', category:'Fruit and Vegetables', emoji:'🌿' },
  { name_en:'Parsley (Fresh)', name_it:'Prezzemolo', category:'Fruit and Vegetables', emoji:'🌿' },
  { name_en:'Mint (Fresh)', name_it:'Menta Fresca', category:'Fruit and Vegetables', emoji:'🌿' },
  { name_en:'Corn on the Cob', name_it:'Mais', category:'Fruit and Vegetables', emoji:'🌽' },
  { name_en:'Green Beans', name_it:'Fagiolini', category:'Fruit and Vegetables', emoji:'🫘' },
  { name_en:'Peas', name_it:'Piselli', category:'Fruit and Vegetables', emoji:'🫛' },

  // Bakery & Bread
  { name_en:'White Bread', name_it:'Pane Bianco', category:'Bakery & Bread', emoji:'🍞' },
  { name_en:'Whole Wheat Bread', name_it:'Pane Integrale', category:'Bakery & Bread', emoji:'🍞' },
  { name_en:'Sourdough Bread', name_it:'Pane a Lievito Madre', category:'Bakery & Bread', emoji:'🍞' },
  { name_en:'Pita Bread', name_it:'Pane Pita', category:'Bakery & Bread', emoji:'🫓' },
  { name_en:'Baguette', name_it:'Baguette', category:'Bakery & Bread', emoji:'🥖' },
  { name_en:'Croissants', name_it:'Cornetti', category:'Bakery & Bread', emoji:'🥐' },
  { name_en:'Brioche', name_it:'Brioche', category:'Bakery & Bread', emoji:'🥐' },
  { name_en:'Burger Buns', name_it:'Panini da Hamburger', category:'Bakery & Bread', emoji:'🍔' },
  { name_en:'Tortilla Wraps', name_it:'Tortillas', category:'Bakery & Bread', emoji:'🫓' },
  { name_en:'Naan Bread', name_it:'Pane Naan', category:'Bakery & Bread', emoji:'🫓' },
  { name_en:'Arabic Bread (Khubz)', name_it:'Pane Arabo', category:'Bakery & Bread', emoji:'🫓' },

  // Fish & Seafood
  { name_en:'Salmon Fillet', name_it:'Filetto di Salmone', category:'Fish & Seafood', emoji:'🐟' },
  { name_en:'Tuna Steak', name_it:'Bistecca di Tonno', category:'Fish & Seafood', emoji:'🐟' },
  { name_en:'Sea Bass', name_it:'Branzino', category:'Fish & Seafood', emoji:'🐟' },
  { name_en:'Hammour (Grouper)', name_it:'Cernia', category:'Fish & Seafood', emoji:'🐟' },
  { name_en:'Prawns', name_it:'Gamberi', category:'Fish & Seafood', emoji:'🍤' },
  { name_en:'Shrimp', name_it:'Gamberetti', category:'Fish & Seafood', emoji:'🍤' },
  { name_en:'Squid', name_it:'Calamari', category:'Fish & Seafood', emoji:'🦑' },
  { name_en:'Crab', name_it:'Granchio', category:'Fish & Seafood', emoji:'🦀' },
  { name_en:'Lobster', name_it:'Aragosta', category:'Fish & Seafood', emoji:'🦞' },
  { name_en:'Tilapia', name_it:'Tilapia', category:'Fish & Seafood', emoji:'🐟' },
  { name_en:'Mussels', name_it:'Cozze', category:'Fish & Seafood', emoji:'🦪' },
  { name_en:'Clams', name_it:'Vongole', category:'Fish & Seafood', emoji:'🦪' },

  // Meat & Poultry
  { name_en:'Chicken Breast', name_it:'Petto di Pollo', category:'Meat & Poultry', emoji:'🍗' },
  { name_en:'Chicken Thighs', name_it:'Cosce di Pollo', category:'Meat & Poultry', emoji:'🍗' },
  { name_en:'Whole Chicken', name_it:'Pollo Intero', category:'Meat & Poultry', emoji:'🍗' },
  { name_en:'Beef Mince', name_it:'Carne Macinata', category:'Meat & Poultry', emoji:'🥩' },
  { name_en:'Beef Steak', name_it:'Bistecca di Manzo', category:'Meat & Poultry', emoji:'🥩' },
  { name_en:'Lamb Chops', name_it:"Costolette d'Agnello", category:'Meat & Poultry', emoji:'🥩' },
  { name_en:'Lamb Mince', name_it:'Agnello Macinato', category:'Meat & Poultry', emoji:'🥩' },
  { name_en:'Veal', name_it:'Vitello', category:'Meat & Poultry', emoji:'🥩' },
  { name_en:'Turkey', name_it:'Tacchino', category:'Meat & Poultry', emoji:'🦃' },
  { name_en:'Beef Burger Patties', name_it:'Hamburger di Manzo', category:'Meat & Poultry', emoji:'🍔' },

  // Deli & Charcuterie
  { name_en:'Turkey Ham', name_it:'Prosciutto di Tacchino', category:'Deli & Charcuterie', emoji:'🍖' },
  { name_en:'Chicken Mortadella', name_it:'Mortadella di Pollo', category:'Deli & Charcuterie', emoji:'🍖' },
  { name_en:'Beef Salami', name_it:'Salame di Manzo', category:'Deli & Charcuterie', emoji:'🍖' },
  { name_en:'Smoked Salmon (Deli)', name_it:'Salmone Affumicato', category:'Deli & Charcuterie', emoji:'🐟' },
  { name_en:'Hummus (Fresh)', name_it:'Hummus Fresco', category:'Deli & Charcuterie', emoji:'🫙' },
  { name_en:'Labneh', name_it:'Labneh', category:'Deli & Charcuterie', emoji:'🫙' },
  { name_en:'Olives (Deli)', name_it:'Olive (Sfuse)', category:'Deli & Charcuterie', emoji:'🫒' },

  // Dairy & Eggs
  { name_en:'Milk (Full Fat)', name_it:'Latte Intero', category:'Dairy & Eggs', emoji:'🥛' },
  { name_en:'Milk (Skimmed)', name_it:'Latte Scremato', category:'Dairy & Eggs', emoji:'🥛' },
  { name_en:'Oat Milk', name_it:'Latte di Avena', category:'Dairy & Eggs', emoji:'🥛' },
  { name_en:'Almond Milk', name_it:'Latte di Mandorle', category:'Dairy & Eggs', emoji:'🥛' },
  { name_en:'Eggs', name_it:'Uova', category:'Dairy & Eggs', emoji:'🥚' },
  { name_en:'Butter', name_it:'Burro', category:'Dairy & Eggs', emoji:'🧈' },
  { name_en:'Cream Cheese', name_it:'Formaggio Cremoso', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Cheddar Cheese', name_it:'Formaggio Cheddar', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Mozzarella', name_it:'Mozzarella', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Feta Cheese', name_it:'Feta', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Halloumi', name_it:'Halloumi', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Parmesan', name_it:'Parmigiano', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Ricotta', name_it:'Ricotta', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Grana Padano', name_it:'Grana Padano', category:'Dairy & Eggs', emoji:'🧀' },
  { name_en:'Yoghurt (Plain)', name_it:'Yogurt Naturale', category:'Dairy & Eggs', emoji:'🫙' },
  { name_en:'Greek Yoghurt', name_it:'Yogurt Greco', category:'Dairy & Eggs', emoji:'🫙' },
  { name_en:'Sour Cream', name_it:'Panna Acida', category:'Dairy & Eggs', emoji:'🫙' },
  { name_en:'Whipping Cream', name_it:'Panna da Montare', category:'Dairy & Eggs', emoji:'🫙' },
  { name_en:'Cooking Cream', name_it:'Panna da Cucina', category:'Dairy & Eggs', emoji:'🫙' },

  // Frozen Foods
  { name_en:'Frozen Peas', name_it:'Piselli Surgelati', category:'Frozen Foods', emoji:'🧊' },
  { name_en:'Frozen Corn', name_it:'Mais Surgelato', category:'Frozen Foods', emoji:'🧊' },
  { name_en:'Frozen Mixed Vegetables', name_it:'Verdure Miste Surgelate', category:'Frozen Foods', emoji:'🧊' },
  { name_en:'Frozen Prawns', name_it:'Gamberi Surgelati', category:'Frozen Foods', emoji:'🧊' },
  { name_en:'Frozen Chicken Nuggets', name_it:'Nuggets di Pollo', category:'Frozen Foods', emoji:'🧊' },
  { name_en:'Frozen Pizza', name_it:'Pizza Surgelata', category:'Frozen Foods', emoji:'🍕' },
  { name_en:'Frozen Fries', name_it:'Patatine Fritte Surgelate', category:'Frozen Foods', emoji:'🍟' },
  { name_en:'Ice Cream', name_it:'Gelato', category:'Frozen Foods', emoji:'🍦' },
  { name_en:'Frozen Waffles', name_it:'Waffle Surgelati', category:'Frozen Foods', emoji:'🧇' },
  { name_en:'Frozen Edamame', name_it:'Edamame Surgelati', category:'Frozen Foods', emoji:'🧊' },

  // Beverages & Juices
  { name_en:'Orange Juice', name_it:'Succo di Arancia', category:'Beverages & Juices', emoji:'🍊' },
  { name_en:'Apple Juice', name_it:'Succo di Mela', category:'Beverages & Juices', emoji:'🍎' },
  { name_en:'Mango Juice', name_it:'Succo di Mango', category:'Beverages & Juices', emoji:'🥭' },
  { name_en:'Coffee (Ground)', name_it:'Caffè Macinato', category:'Beverages & Juices', emoji:'☕' },
  { name_en:'Coffee (Instant)', name_it:'Caffè Solubile', category:'Beverages & Juices', emoji:'☕' },
  { name_en:'Coffee Pods', name_it:'Cialde Caffè', category:'Beverages & Juices', emoji:'☕' },
  { name_en:'Tea Bags', name_it:'Bustine di Tè', category:'Beverages & Juices', emoji:'🍵' },
  { name_en:'Green Tea', name_it:'Tè Verde', category:'Beverages & Juices', emoji:'🍵' },
  { name_en:'Herbal Tea', name_it:'Tisana', category:'Beverages & Juices', emoji:'🍵' },
  { name_en:'Protein Shake', name_it:'Frullato Proteico', category:'Beverages & Juices', emoji:'💪' },

  // Water & Soft Drinks
  { name_en:'Water (Still)', name_it:'Acqua Naturale', category:'Water & Soft Drinks', emoji:'💧' },
  { name_en:'Water (Sparkling)', name_it:'Acqua Frizzante', category:'Water & Soft Drinks', emoji:'💧' },
  { name_en:'Coca-Cola', name_it:'Coca-Cola', category:'Water & Soft Drinks', emoji:'🥤' },
  { name_en:'Pepsi', name_it:'Pepsi', category:'Water & Soft Drinks', emoji:'🥤' },
  { name_en:'Sprite', name_it:'Sprite', category:'Water & Soft Drinks', emoji:'🥤' },
  { name_en:'7UP', name_it:'7UP', category:'Water & Soft Drinks', emoji:'🥤' },
  { name_en:'Fanta', name_it:'Fanta', category:'Water & Soft Drinks', emoji:'🥤' },
  { name_en:'Red Bull', name_it:'Red Bull', category:'Water & Soft Drinks', emoji:'⚡' },
  { name_en:'Coconut Water', name_it:'Acqua di Cocco', category:'Water & Soft Drinks', emoji:'🥥' },

  // Breakfast & Cereals
  { name_en:'Cornflakes', name_it:'Cornflakes', category:'Breakfast & Cereals', emoji:'🥣' },
  { name_en:'Granola', name_it:'Granola', category:'Breakfast & Cereals', emoji:'🥣' },
  { name_en:'Muesli', name_it:'Muesli', category:'Breakfast & Cereals', emoji:'🥣' },
  { name_en:'Oats / Porridge', name_it:'Fiocchi di Avena', category:'Breakfast & Cereals', emoji:'🥣' },
  { name_en:'Nutella', name_it:'Nutella', category:'Breakfast & Cereals', emoji:'🍫' },
  { name_en:'Peanut Butter', name_it:'Burro di Arachidi', category:'Breakfast & Cereals', emoji:'🥜' },
  { name_en:'Almond Butter', name_it:'Burro di Mandorle', category:'Breakfast & Cereals', emoji:'🥜' },
  { name_en:'Jam / Preserves', name_it:'Marmellata', category:'Breakfast & Cereals', emoji:'🍓' },
  { name_en:'Honey', name_it:'Miele', category:'Breakfast & Cereals', emoji:'🍯' },
  { name_en:'Maple Syrup', name_it:"Sciroppo d'Acero", category:'Breakfast & Cereals', emoji:'🍯' },

  // Pasta, Rice & Grains
  { name_en:'Basmati Rice', name_it:'Riso Basmati', category:'Pasta, Rice & Grains', emoji:'🍚' },
  { name_en:'White Rice', name_it:'Riso Bianco', category:'Pasta, Rice & Grains', emoji:'🍚' },
  { name_en:'Brown Rice', name_it:'Riso Integrale', category:'Pasta, Rice & Grains', emoji:'🍚' },
  { name_en:'Arborio Rice', name_it:'Riso Arborio', category:'Pasta, Rice & Grains', emoji:'🍚' },
  { name_en:'Quinoa', name_it:'Quinoa', category:'Pasta, Rice & Grains', emoji:'🌾' },
  { name_en:'Couscous', name_it:'Cous Cous', category:'Pasta, Rice & Grains', emoji:'🌾' },
  { name_en:'Bulgur Wheat', name_it:'Bulgur', category:'Pasta, Rice & Grains', emoji:'🌾' },
  { name_en:'Pasta (Spaghetti)', name_it:'Spaghetti', category:'Pasta, Rice & Grains', emoji:'🍝' },
  { name_en:'Pasta (Penne)', name_it:'Penne', category:'Pasta, Rice & Grains', emoji:'🍝' },
  { name_en:'Pasta (Fusilli)', name_it:'Fusilli', category:'Pasta, Rice & Grains', emoji:'🍝' },
  { name_en:'Pasta (Lasagne)', name_it:'Lasagne', category:'Pasta, Rice & Grains', emoji:'🍝' },
  { name_en:'Pasta (Rigatoni)', name_it:'Rigatoni', category:'Pasta, Rice & Grains', emoji:'🍝' },
  { name_en:'Pasta (Farfalle)', name_it:'Farfalle', category:'Pasta, Rice & Grains', emoji:'🍝' },
  { name_en:'Noodles', name_it:'Noodles', category:'Pasta, Rice & Grains', emoji:'🍜' },
  { name_en:'Lentils', name_it:'Lenticchie', category:'Pasta, Rice & Grains', emoji:'🫘' },
  { name_en:'Chickpeas (Dry)', name_it:'Ceci Secchi', category:'Pasta, Rice & Grains', emoji:'🫘' },

  // Canned & Jarred Goods
  { name_en:'Canned Tomatoes', name_it:'Pomodori Pelati', category:'Canned & Jarred Goods', emoji:'🥫' },
  { name_en:'Canned Chickpeas', name_it:'Ceci in Scatola', category:'Canned & Jarred Goods', emoji:'🥫' },
  { name_en:'Canned Lentils', name_it:'Lenticchie in Scatola', category:'Canned & Jarred Goods', emoji:'🥫' },
  { name_en:'Canned Tuna', name_it:'Tonno in Scatola', category:'Canned & Jarred Goods', emoji:'🥫' },
  { name_en:'Canned Sardines', name_it:'Sardine in Scatola', category:'Canned & Jarred Goods', emoji:'🥫' },
  { name_en:'Canned Corn', name_it:'Mais in Scatola', category:'Canned & Jarred Goods', emoji:'🌽' },
  { name_en:'Canned Coconut Milk', name_it:'Latte di Cocco', category:'Canned & Jarred Goods', emoji:'🥫' },
  { name_en:'Olives (Jar)', name_it:'Olive in Barattolo', category:'Canned & Jarred Goods', emoji:'🫒' },
  { name_en:'Sun-Dried Tomatoes', name_it:'Pomodori Secchi', category:'Canned & Jarred Goods', emoji:'🍅' },
  { name_en:'Artichoke Hearts', name_it:'Cuori di Carciofo', category:'Canned & Jarred Goods', emoji:'🥫' },

  // Sauces & Condiments
  { name_en:'Tomato Sauce / Passata', name_it:'Passata di Pomodoro', category:'Sauces & Condiments', emoji:'🍅' },
  { name_en:'Pasta Sauce', name_it:'Sugo per Pasta', category:'Sauces & Condiments', emoji:'🍝' },
  { name_en:'Ketchup', name_it:'Ketchup', category:'Sauces & Condiments', emoji:'🍅' },
  { name_en:'Mayonnaise', name_it:'Maionese', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Mustard', name_it:'Senape', category:'Sauces & Condiments', emoji:'🌭' },
  { name_en:'Soy Sauce', name_it:'Salsa di Soia', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Hot Sauce / Tabasco', name_it:'Salsa Piccante', category:'Sauces & Condiments', emoji:'🌶️' },
  { name_en:'BBQ Sauce', name_it:'Salsa BBQ', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Tahini', name_it:'Tahini', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Pesto', name_it:'Pesto', category:'Sauces & Condiments', emoji:'🌿' },
  { name_en:'Vinegar (White)', name_it:'Aceto Bianco', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Apple Cider Vinegar', name_it:'Aceto di Mele', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Balsamic Vinegar', name_it:'Aceto Balsamico', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Olive Oil', name_it:"Olio d'Oliva", category:'Sauces & Condiments', emoji:'🫒' },
  { name_en:'Extra Virgin Olive Oil', name_it:"Olio d'Oliva Extravergine", category:'Sauces & Condiments', emoji:'🫒' },
  { name_en:'Sunflower Oil', name_it:'Olio di Girasole', category:'Sauces & Condiments', emoji:'🌻' },
  { name_en:'Vegetable Oil', name_it:'Olio Vegetale', category:'Sauces & Condiments', emoji:'🫙' },
  { name_en:'Sesame Oil', name_it:'Olio di Sesamo', category:'Sauces & Condiments', emoji:'🫙' },

  // Spices & Cooking
  { name_en:'Salt', name_it:'Sale', category:'Spices & Cooking', emoji:'🧂' },
  { name_en:'Black Pepper', name_it:'Pepe Nero', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Cumin', name_it:'Cumino', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Coriander (Ground)', name_it:'Coriandolo in Polvere', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Turmeric', name_it:'Curcuma', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Paprika', name_it:'Paprika', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Cinnamon', name_it:'Cannella', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Cardamom', name_it:'Cardamomo', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Chilli Powder', name_it:'Peperoncino in Polvere', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Garam Masala', name_it:'Garam Masala', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Oregano', name_it:'Origano', category:'Spices & Cooking', emoji:'🌿' },
  { name_en:'Basil (Dried)', name_it:'Basilico Secco', category:'Spices & Cooking', emoji:'🌿' },
  { name_en:'Rosemary', name_it:'Rosmarino', category:'Spices & Cooking', emoji:'🌿' },
  { name_en:'Thyme', name_it:'Timo', category:'Spices & Cooking', emoji:'🌿' },
  { name_en:'Zaatar', name_it:'Zaatar', category:'Spices & Cooking', emoji:'🌿' },
  { name_en:'Sumac', name_it:'Sommacco', category:'Spices & Cooking', emoji:'🌶️' },
  { name_en:'Chicken Stock / Cube', name_it:'Dado di Pollo', category:'Spices & Cooking', emoji:'🍗' },
  { name_en:'Vegetable Stock', name_it:'Brodo Vegetale', category:'Spices & Cooking', emoji:'🥦' },

  // Baking & Confectionery
  { name_en:'Plain Flour', name_it:'Farina 00', category:'Baking & Confectionery', emoji:'🌾' },
  { name_en:'Self-Raising Flour', name_it:'Farina con Lievito', category:'Baking & Confectionery', emoji:'🌾' },
  { name_en:'Sugar (White)', name_it:'Zucchero Bianco', category:'Baking & Confectionery', emoji:'🍬' },
  { name_en:'Sugar (Brown)', name_it:'Zucchero di Canna', category:'Baking & Confectionery', emoji:'🍬' },
  { name_en:'Icing Sugar', name_it:'Zucchero a Velo', category:'Baking & Confectionery', emoji:'🍬' },
  { name_en:'Baking Powder', name_it:'Lievito per Dolci', category:'Baking & Confectionery', emoji:'🎂' },
  { name_en:'Baking Soda', name_it:'Bicarbonato di Sodio', category:'Baking & Confectionery', emoji:'🎂' },
  { name_en:'Vanilla Extract', name_it:'Estratto di Vaniglia', category:'Baking & Confectionery', emoji:'🌿' },
  { name_en:'Cocoa Powder', name_it:'Cacao in Polvere', category:'Baking & Confectionery', emoji:'🍫' },
  { name_en:'Dark Chocolate', name_it:'Cioccolato Fondente', category:'Baking & Confectionery', emoji:'🍫' },
  { name_en:'Milk Chocolate', name_it:'Cioccolato al Latte', category:'Baking & Confectionery', emoji:'🍫' },
  { name_en:'Chocolate Chips', name_it:'Gocce di Cioccolato', category:'Baking & Confectionery', emoji:'🍫' },
  { name_en:'Yeast (Dry)', name_it:'Lievito di Birra Secco', category:'Baking & Confectionery', emoji:'🍞' },
  { name_en:'Condensed Milk', name_it:'Latte Condensato', category:'Baking & Confectionery', emoji:'🥛' },

  // Snacks & Biscuits
  { name_en:'Potato Chips / Crisps', name_it:'Patatine', category:'Snacks & Biscuits', emoji:'🍟' },
  { name_en:'Popcorn', name_it:'Popcorn', category:'Snacks & Biscuits', emoji:'🍿' },
  { name_en:'Mixed Nuts', name_it:'Frutta Secca Mista', category:'Snacks & Biscuits', emoji:'🥜' },
  { name_en:'Almonds', name_it:'Mandorle', category:'Snacks & Biscuits', emoji:'🥜' },
  { name_en:'Cashews', name_it:'Anacardi', category:'Snacks & Biscuits', emoji:'🥜' },
  { name_en:'Pistachios', name_it:'Pistacchi', category:'Snacks & Biscuits', emoji:'🥜' },
  { name_en:'Walnuts', name_it:'Noci', category:'Snacks & Biscuits', emoji:'🥜' },
  { name_en:'Dates', name_it:'Datteri', category:'Snacks & Biscuits', emoji:'🌴' },
  { name_en:'Digestive Biscuits', name_it:'Biscotti Digestive', category:'Snacks & Biscuits', emoji:'🍪' },
  { name_en:'Oreos', name_it:'Oreo', category:'Snacks & Biscuits', emoji:'🍪' },
  { name_en:'Rice Cakes', name_it:'Gallette di Riso', category:'Snacks & Biscuits', emoji:'🍘' },
  { name_en:'Protein Bars', name_it:'Barrette Proteiche', category:'Snacks & Biscuits', emoji:'💪' },
  { name_en:'Granola Bars', name_it:'Barrette ai Cereali', category:'Snacks & Biscuits', emoji:'🥣' },

  // International Foods
  { name_en:'Sushi Rice', name_it:'Riso per Sushi', category:'International Foods', emoji:'🍱' },
  { name_en:'Miso Paste', name_it:'Pasta di Miso', category:'International Foods', emoji:'🍜' },
  { name_en:'Thai Curry Paste', name_it:'Pasta Curry Thai', category:'International Foods', emoji:'🍛' },
  { name_en:'Fish Sauce', name_it:'Salsa di Pesce', category:'International Foods', emoji:'🐟' },
  { name_en:'Oyster Sauce', name_it:'Salsa di Ostriche', category:'International Foods', emoji:'🦪' },
  { name_en:'Taco Shells', name_it:'Taco', category:'International Foods', emoji:'🌮' },
  { name_en:'Salsa', name_it:'Salsa Messicana', category:'International Foods', emoji:'🌮' },
  { name_en:'Harissa Paste', name_it:'Harissa', category:'International Foods', emoji:'🌶️' },
  { name_en:'Kimchi', name_it:'Kimchi', category:'International Foods', emoji:'🥬' },

  // Health & Organic
  { name_en:'Chia Seeds', name_it:'Semi di Chia', category:'Health & Organic', emoji:'🌱' },
  { name_en:'Flaxseeds', name_it:'Semi di Lino', category:'Health & Organic', emoji:'🌱' },
  { name_en:'Hemp Seeds', name_it:'Semi di Canapa', category:'Health & Organic', emoji:'🌱' },
  { name_en:'Protein Powder', name_it:'Proteine in Polvere', category:'Health & Organic', emoji:'💪' },
  { name_en:'Vitamin C Supplements', name_it:'Vitamina C', category:'Health & Organic', emoji:'💊' },
  { name_en:'Multivitamins', name_it:'Multivitaminici', category:'Health & Organic', emoji:'💊' },

  // Baby & Infant
  { name_en:'Baby Formula', name_it:'Latte in Polvere per Neonati', category:'Baby & Infant', emoji:'🍼' },
  { name_en:'Baby Food (Jars)', name_it:'Omogeneizzati', category:'Baby & Infant', emoji:'🫙' },
  { name_en:'Baby Cereal', name_it:'Cereali per Bambini', category:'Baby & Infant', emoji:'🥣' },
  { name_en:'Nappies / Diapers', name_it:'Pannolini', category:'Baby & Infant', emoji:'👶' },
  { name_en:'Baby Wipes', name_it:'Salviettine per Bambini', category:'Baby & Infant', emoji:'🧻' },

  // Health & Beauty
  { name_en:'Shampoo', name_it:'Shampoo', category:'Health & Beauty', emoji:'🧴' },
  { name_en:'Conditioner', name_it:'Balsamo', category:'Health & Beauty', emoji:'🧴' },
  { name_en:'Body Wash / Shower Gel', name_it:'Bagnoschiuma', category:'Health & Beauty', emoji:'🚿' },
  { name_en:'Face Wash', name_it:'Detergente Viso', category:'Health & Beauty', emoji:'🧴' },
  { name_en:'Moisturiser', name_it:'Crema Idratante', category:'Health & Beauty', emoji:'🧴' },
  { name_en:'Sunscreen SPF 50', name_it:'Crema Solare SPF 50', category:'Health & Beauty', emoji:'☀️' },
  { name_en:'Deodorant', name_it:'Deodorante', category:'Health & Beauty', emoji:'🧴' },
  { name_en:'Toothpaste', name_it:'Dentifricio', category:'Health & Beauty', emoji:'🪥' },
  { name_en:'Toothbrush', name_it:'Spazzolino', category:'Health & Beauty', emoji:'🪥' },
  { name_en:'Mouthwash', name_it:'Collutorio', category:'Health & Beauty', emoji:'🧴' },
  { name_en:'Razor', name_it:'Rasoio', category:'Health & Beauty', emoji:'🪒' },
  { name_en:'Cotton Buds', name_it:'Cotton Fioc', category:'Health & Beauty', emoji:'🧻' },
  { name_en:'Paracetamol', name_it:'Paracetamolo', category:'Health & Beauty', emoji:'💊' },
  { name_en:'Ibuprofen', name_it:'Ibuprofene', category:'Health & Beauty', emoji:'💊' },

  // Cleaning & Laundry
  { name_en:'Washing Up Liquid', name_it:'Detersivo per Piatti', category:'Cleaning & Laundry', emoji:'🧼' },
  { name_en:'Dishwasher Tablets', name_it:'Pastiglie Lavastoviglie', category:'Cleaning & Laundry', emoji:'🍽️' },
  { name_en:'Laundry Detergent', name_it:'Detersivo per Lavatrice', category:'Cleaning & Laundry', emoji:'🧺' },
  { name_en:'Fabric Softener', name_it:'Ammorbidente', category:'Cleaning & Laundry', emoji:'🧺' },
  { name_en:'All-Purpose Cleaner', name_it:'Detergente Multiuso', category:'Cleaning & Laundry', emoji:'🧹' },
  { name_en:'Bleach', name_it:'Candeggina', category:'Cleaning & Laundry', emoji:'🧪' },
  { name_en:'Glass Cleaner', name_it:'Vetrocleaner', category:'Cleaning & Laundry', emoji:'🪟' },
  { name_en:'Floor Cleaner', name_it:'Detergente per Pavimenti', category:'Cleaning & Laundry', emoji:'🧹' },
  { name_en:'Toilet Cleaner', name_it:'Anticalcare WC', category:'Cleaning & Laundry', emoji:'🚽' },
  { name_en:'Scrubbing Sponge', name_it:'Spugna Abrasiva', category:'Cleaning & Laundry', emoji:'🧽' },

  // Paper & Disposables
  { name_en:'Toilet Paper', name_it:'Carta Igienica', category:'Paper & Disposables', emoji:'🧻' },
  { name_en:'Kitchen Paper / Tissues', name_it:'Carta da Cucina', category:'Paper & Disposables', emoji:'🧻' },
  { name_en:'Facial Tissues', name_it:'Fazzoletti', category:'Paper & Disposables', emoji:'🤧' },
  { name_en:'Bin Liners / Garbage Bags', name_it:'Sacchetti Spazzatura', category:'Paper & Disposables', emoji:'🗑️' },
  { name_en:'Cling Film / Plastic Wrap', name_it:'Pellicola Trasparente', category:'Paper & Disposables', emoji:'🧻' },
  { name_en:'Aluminium Foil', name_it:'Carta Stagnola', category:'Paper & Disposables', emoji:'🔧' },
  { name_en:'Baking Parchment', name_it:'Carta da Forno', category:'Paper & Disposables', emoji:'🎂' },
  { name_en:'Zip Lock Bags', name_it:'Sacchetti Zip', category:'Paper & Disposables', emoji:'🛍️' },

  // Pet Food & Supplies
  { name_en:'Cat Food (Dry)', name_it:'Cibo per Gatti (Secco)', category:'Pet Food & Supplies', emoji:'🐱' },
  { name_en:'Cat Food (Wet)', name_it:'Cibo per Gatti (Umido)', category:'Pet Food & Supplies', emoji:'🐱' },
  { name_en:'Dog Food (Dry)', name_it:'Cibo per Cani (Secco)', category:'Pet Food & Supplies', emoji:'🐶' },
  { name_en:'Dog Food (Wet)', name_it:'Cibo per Cani (Umido)', category:'Pet Food & Supplies', emoji:'🐶' },
  { name_en:'Cat Litter', name_it:'Lettiera per Gatti', category:'Pet Food & Supplies', emoji:'🐱' },
  { name_en:'Pet Treats', name_it:'Snack per Animali', category:'Pet Food & Supplies', emoji:'🐾' },
];

const CATEGORIES = [
  'Fruit and Vegetables','Bakery & Bread','Fish & Seafood','Meat & Poultry',
  'Deli & Charcuterie','Dairy & Eggs','Frozen Foods','Beverages & Juices',
  'Water & Soft Drinks','Breakfast & Cereals','Pasta, Rice & Grains',
  'Canned & Jarred Goods','Sauces & Condiments','Spices & Cooking',
  'Baking & Confectionery','Snacks & Biscuits','International Foods',
  'Health & Organic','Baby & Infant','Health & Beauty','Cleaning & Laundry',
  'Paper & Disposables','Pet Food & Supplies','General',
];

const EDIBLE_CATEGORIES = new Set([
  'Fruit and Vegetables','Bakery & Bread','Fish & Seafood','Meat & Poultry',
  'Deli & Charcuterie','Dairy & Eggs','Frozen Foods','Beverages & Juices',
  'Water & Soft Drinks','Breakfast & Cereals','Pasta, Rice & Grains',
  'Canned & Jarred Goods','Sauces & Condiments','Spices & Cooking',
  'Baking & Confectionery','Snacks & Biscuits','International Foods',
  'Health & Organic','General',
]);

const LIST_EMOJIS = ['🛒','🍎','🥗','🍕','🏠','🎉','🌴','🏋️','👶','🐾','🌿','❤️','🎂','🧴','✈️'];

const SUGGESTED_EMOJIS = [
  '🍎','🍊','🍋','🍇','🍓','🫐','🍑','🥭','🍅','🥝','🥦','🥕','🧅','🧄','🥔','🌽',
  '🎃','🥩','🍗','🐟','🥚','🧀','🥛','🧈','🍞','🥐','🍝','🍚','🥫','🫙','🧃','💧',
  '🧂','🌶️','🫒','🍫','🍪','🧁','🧴','🧼','🧹','🧻','🐾','👶','🌿','🥣','🍵','☕','🧊',
];

/* Default example supermarket: Carrefour Mirdif City Centre aisle layout,
   ported verbatim, tagged with the ITEM_DB category it best matches so
   aisle-sort works out of the box. Categories with no matching aisle here
   (fresh produce/meat/bakery/deli, spices, etc.) fall under "General" until
   the user customises this store's aisles in Settings. */
const DEFAULT_SUPERMARKET_AISLES = [
  { num: 30, label: 'Aisle 30 — Hair Care',             emoji: '💇', category: 'Health & Beauty' },
  { num: 31, label: 'Aisle 31 — Personal Hygiene',      emoji: '🧼', category: 'Health & Beauty' },
  { num: 32, label: 'Aisle 32 — Men Care',              emoji: '🪒', category: 'Health & Beauty' },
  { num: 33, label: 'Aisle 33 — Women Care',            emoji: '🌸', category: 'Health & Beauty' },
  { num: 34, label: 'Aisle 34 — Make Up & Skin Care',   emoji: '💄', category: 'Health & Beauty' },
  { num: 35, label: 'Aisle 35 — Baking Essentials',     emoji: '🌾', category: 'Baking & Confectionery' },
  { num: 36, label: 'Aisle 36 — Breakfast',             emoji: '☕', category: 'Breakfast & Cereals' },
  { num: 37, label: 'Aisle 37 — Chocolate & Candy',     emoji: '🍫', category: 'Snacks & Biscuits' },
  { num: 39, label: 'Aisle 39 — Biscuits & Cookies',    emoji: '🍪', category: 'Snacks & Biscuits' },
  { num: 40, label: 'Aisle 40 — Frozen Food',           emoji: '🍗', category: 'Frozen Foods' },
  { num: 41, label: 'Aisle 41 — Frozen Desserts',       emoji: '🍦', category: 'Frozen Foods' },
  { num: 42, label: 'Aisle 42 — Dairy',                 emoji: '🥛', category: 'Dairy & Eggs' },
  { num: 43, label: 'Aisle 43 — Frozen Seafood',        emoji: '🐟', category: 'Fish & Seafood' },
  { num: 44, label: 'Aisle 44 — Coffee & Tea',          emoji: '🍵', category: 'Beverages & Juices' },
  { num: 45, label: 'Aisle 45 — Snacks & Rice Cakes',   emoji: '🍿', category: 'Snacks & Biscuits' },
  { num: 46, label: 'Aisle 46 — Beverages',             emoji: '🧃', category: 'Beverages & Juices' },
  { num: 47, label: 'Aisle 47 — Snacks & Nuts',         emoji: '🥜', category: 'Snacks & Biscuits' },
  { num: 48, label: 'Aisle 48 — Rice, Pulses & Pasta',  emoji: '🍚', category: 'Pasta, Rice & Grains' },
  { num: 49, label: 'Aisle 49 — Ready to Eat',          emoji: '🥫', category: 'Canned & Jarred Goods' },
  { num: 50, label: 'Aisle 50 — Cooking Oils & Sauces', emoji: '🫒', category: 'Sauces & Condiments' },
  { num: 51, label: 'Aisle 51 — Cuisine of the World',  emoji: '🌍', category: 'International Foods' },
  { num: 52, label: 'Aisle 52 — Laundry & Cleaning',    emoji: '🧺', category: 'Cleaning & Laundry' },
  { num: 53, label: 'Aisle 53 — Home Care',             emoji: '🧹', category: 'Cleaning & Laundry' },
  { num: 54, label: 'Aisle 54 — Baby Essentials',       emoji: '🍼', category: 'Baby & Infant' },
  { num: 55, label: 'Aisle 55 — Baby Care',             emoji: '👶', category: 'Baby & Infant' },
];

const GENERAL_AISLE = { aisleNumber: 999, label: 'General', emoji: '🛒', category: 'General' };

/* ── Emoji keyword inference (fallback when nothing in ITEM_DB/custom matches) ── */
const EMOJI_KEYWORDS = [
  ['🎃', ['butternut squash','butternut','acorn squash','spaghetti squash','delicata squash','kabocha squash']],
  ['🍎', ['apple','mela','granny','fuji','gala','braeburn']],
  ['🍐', ['pear','pera','conference','williams']],
  ['🍊', ['orange','arancia','clementine','mandarin','tangerine','mandarino']],
  ['🍋', ['lemon','limone','lime','cedro']],
  ['🍇', ['grape','uva','grapes','raisin','sultanina']],
  ['🍓', ['strawberry','fragola','fragole']],
  ['🫐', ['blueberry','mirtillo','blueberries']],
  ['🍒', ['cherry','ciliegia','ciliegie','morello']],
  ['🍑', ['peach','pesca','nectarine','percoca']],
  ['🥭', ['mango','mangoes']],
  ['🍍', ['pineapple','ananas']],
  ['🥥', ['coconut','cocco','noce di cocco']],
  ['🍌', ['banana','banane']],
  ['🍉', ['watermelon','anguria','cocomero']],
  ['🍈', ['melon','melone','honeydew','cantaloupe']],
  ['🫒', ['olive','olives','olive oil','olio oliva']],
  ['🎃', ['pumpkin','squash','butternut','zucca','courgette squash','acorn squash','spaghetti squash','delicata','kabocha']],
  ['🍆', ['eggplant','aubergine','melanzana','melanzane']],
  ['🥑', ['avocado']],
  ['🥝', ['kiwi']],
  ['🍅', ['tomato','pomodoro','pomodori','cherry tomato']],
  ['🌽', ['corn','mais','sweetcorn','polenta']],
  ['🥕', ['carrot','carota','carote']],
  ['🧅', ['onion','cipolla','cipolle','shallot','scalogno']],
  ['🧄', ['garlic','aglio']],
  ['🥔', ['potato','patata','patate','sweet potato','batata']],
  ['🥦', ['broccoli']],
  ['🥬', ['lettuce','lattuga','spinach','spinaci','kale','cabbage','cavolo','chard','bietola','rocket','rucola','salad','insalata','endive','indivia']],
  ['🥒', ['cucumber','cetriolo','cetrioli','courgette','zucchini','zucchine']],
  ['🫑', ['pepper','peperone','peperoni','capsicum','bell pepper']],
  ['🌶', ['chili','chilli','peperoncino','jalapeño','cayenne']],
  ['🍄', ['mushroom','fungo','funghi','porcini','champignon']],
  ['🌿', ['herb','erba','basil','basilico','parsley','prezzemolo','coriander','cilantro','rosemary','rosmarino','thyme','timo','mint','menta','oregano','origano','sage','salvia','dill','aneto']],
  ['🫛', ['pea','pisello','piselli','edamame','bean','fagiolo','fagioli','lentil','lenticchia','lenticchie','chickpea','ceci']],
  ['🥜', ['peanut','arachide','arachidi','nut','noce','noci','almond','mandorla','mandorle','walnut','cashew','anacardio','pistachio','pistacchio','hazelnut','nocciola']],
  ['🥚', ['egg','uovo','uova']],
  ['🧀', ['cheese','formaggio','parmesan','parmigiano','mozzarella','ricotta','grana','pecorino','gorgonzola','brie','cheddar','emmental','gouda']],
  ['🥛', ['milk','latte','oat milk','almond milk','soy milk','latte di soia']],
  ['🧈', ['butter','burro','margarine','margarina']],
  ['🍦', ['cream','panna','yogurt','yoghurt','kefir']],
  ['🥩', ['beef','manzo','steak','bistecca','veal','vitello','lamb','agnello','pork','maiale','mince','mincemeat','macinato','ribs','costine']],
  ['🍗', ['chicken','pollo','turkey','tacchino','duck','anatra','poultry']],
  ['🥓', ['bacon','pancetta','ham','prosciutto','salami','salame','sausage','salsiccia','mortadella','bresaola','speck','guanciale','lardo','coppa']],
  ['🐟', ['fish','pesce','cod','merluzzo','salmon','salmone','tuna','tonno','sea bass','branzino','sea bream','orata','sardine','sardina','anchovy','acciuga','anchova','trout','trota','tilapia','hake','nasello']],
  ['🦐', ['shrimp','gamberetto','prawn','gambero','gamberi','scampi']],
  ['🦑', ['squid','calamaro','calamari','octopus','polpo','cuttlefish','seppia']],
  ['🦞', ['lobster','astice','aragosta','crab','granchio','clam','vongola','mussel','cozza','oyster','ostrica']],
  ['🍞', ['bread','pane','loaf','baguette','ciabatta','focaccia','roll','panino','toast','sourdough','lievito madre','brioche','rye','segale','whole wheat','integrale']],
  ['🥐', ['croissant','cornetto']],
  ['🥨', ['cracker','cracker','grissini','breadstick']],
  ['🍰', ['cake','torta','pie','crostata','tart','cheesecake','brownie','muffin','pastry','pasta frolla','sfoglia']],
  ['🍪', ['cookie','biscuit','biscotto','biscotti','shortbread','wafer']],
  ['🥞', ['pancake','waffle','crepe','cialda']],
  ['🍝', ['pasta','spaghetti','penne','rigatoni','tagliatelle','fettuccine','fusilli','farfalle','linguine','bucatini','lasagna','lasagne','gnocchi','orecchiette','tortellini','ravioli','noodle']],
  ['🍚', ['rice','riso','arborio','basmati','jasmine','risotto']],
  ['🌾', ['flour','farina','semolina','semola','oat','avena','grain','cereale','cereal','muesli','granola','quinoa','couscous','bulgur','barley','orzo','spelt','farro']],
  ['🥫', ['can','tin','canned','conserva','passata','puree','tomato sauce','sugo','chickpea','beans','tuna in','sardine in','anchovy in']],
  ['🫙', ['jar','vasetto','jam','marmellata','honey','miele','nutella','peanut butter','tahini','pickle','sottaceto','gherkin','cetriolino']],
  ['🫙', ['sauce','salsa','ketchup','mustard','senape','mayonnaise','maionese','vinegar','aceto','soy sauce','teriyaki','pesto','hummus','aioli']],
  ['🫒', ['oil','olio','olive oil','sunflower oil','vegetable oil']],
  ['🧂', ['salt','sale','pepper','pepe','spice','spezia','paprika','cumin','cumino','turmeric','curcuma','cinnamon','cannella','nutmeg','noce moscata','curry','chili flakes','peperoncino']],
  ['🧊', ['frozen','surgelato','surgelati','ice cream','gelato','sorbet','sorbetto','popsicle','ghiacciolo']],
  ['☕', ['coffee','caffè','espresso','cappuccino','macchiato','nescafé','tea','tè','chai','matcha']],
  ['🍵', ['herbal tea','camomile','camomilla','infusion','tisana']],
  ['🧃', ['juice','succo','smoothie','nectar','nettare']],
  ['🥤', ['soda','cola','sprite','fanta','energy drink','gatorade','soft drink','fizzy','sparkling']],
  ['💧', ['water','acqua','mineral water','acqua minerale','sparkling water','acqua frizzante']],
  ['🍺', ['beer','birra','ale','lager','stout']],
  ['🍷', ['wine','vino','prosecco','champagne','rosé','rosato']],
  ['🍸', ['gin','vodka','rum','whisky','whiskey','liqueur','liquore','aperol','campari','vermouth']],
  ['🍫', ['chocolate','cioccolato','cocoa','cacao','nutella','choc']],
  ['🍬', ['candy','caramella','caramelle','sweet','sweets','jelly','gummy']],
  ['🍭', ['lollipop','lecca lecca']],
  ['🍿', ['popcorn']],
  ['🥨', ['chip','chips','crisp','crisps','snack','pretzel']],
  ['🧹', ['broom','scopa','mop','floor cleaner','detergent floor']],
  ['🧽', ['sponge','spugna','dish soap','detergent','detersivo','washing up','fairy','vim','ajax','cif']],
  ['🧴', ['shampoo','conditioner','shower gel','gel doccia','body wash','lotion','cream','body lotion','hand cream','soap','sapone','body cream','face wash','cleanser']],
  ['🧻', ['toilet paper','carta igienica','kitchen roll','kitchen paper','paper towel','tissue','fazzoletto','napkin','tovagliolo']],
  ['🪣', ['bleach','candeggina','ammonia','ammoniaca','disinfectant']],
  ['🫧', ['detergent','laundry','washing powder','detersivo lavatrice','softener','ammorbidente','fabric conditioner']],
  ['👶', ['baby','neonato','infant','formula','pampers','nappy','diaper','pannolino','wipes','salviette']],
  ['🐾', ['pet food','dog food','cat food','crocchette','kibble','treat','snack cane','snack gatto']],
  ['💊', ['vitamin','vitamina','supplement','integratore','medicine','medicina','aspirin','paracetamol','ibuprofen','tablet','capsule']],
  ['🪥', ['toothbrush','spazzolino','toothpaste','dentifricio','mouthwash','collutorio','floss']],
  ['🪒', ['razor','rasoio','shaving','schiuma da barba','aftershave']],
  ['🧖', ['mask','mascara','lipstick','makeup','foundation','concealer','eyeliner','blush','perfume','profumo','deodorant','deodorante']],
];

function inferEmoji(lower) {
  for (const pass of ['word', 'substr']) {
    for (const [emoji, keywords] of EMOJI_KEYWORDS) {
      for (const kw of keywords) {
        const match = pass === 'word'
          ? new RegExp(`(^|\\s)${kw.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(\\s|$)`).test(lower)
          : lower.includes(kw);
        if (match) return emoji;
      }
    }
  }
  return null;
}
